### ISSUE TITLE
Alarm not working

### ISSUE THREAD

**Issue by doudz** [doudz/zigate#11]
b'\x1e\x01\x05\x00\x02\tc\x00\x01\x00\xff\x00\x00'
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/doudz/MEGA/Dev/zigate/zigate/transport.py", line 61, in packet_received
    dispatcher.send(ZIGATE_PACKET_RECEIVED, packet=raw_message)
  File "/home/doudz/.local/lib/python3.6/site-packages/pydispatch/dispatcher.py", line 338, in send
    **named
  File "/home/doudz/.local/lib/python3.6/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/home/doudz/MEGA/Dev/zigate/zigate/core.py", line 318, in decode_data
    response = RESPONSES.get(msg_type, Response)(value, rssi)
  File "/home/doudz/MEGA/Dev/zigate/zigate/responses.py", line 45, in __init__
    self.decode()
  File "/home/doudz/MEGA/Dev/zigate/zigate/responses.py", line 106, in decode
    sdata, msg_data = self.__decode(fmt, keys, msg_data)
  File "/home/doudz/MEGA/Dev/zigate/zigate/responses.py", line 117, in __decode
    sdata = OrderedDict(zip(keys, struct.unpack(fmt, data[:size])))
struct.error: unpack requires a buffer of 14 bytes

b'\x1f\x01\x05\x00\x02\tc\x00\x00\x00\xff\x00\x00'
Exception in thread Thread-17:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/doudz/MEGA/Dev/zigate/zigate/transport.py", line 61, in packet_received
    dispatcher.send(ZIGATE_PACKET_RECEIVED, packet=raw_message)
  File "/home/doudz/.local/lib/python3.6/site-packages/pydispatch/dispatcher.py", line 338, in send
    **named
  File "/home/doudz/.local/lib/python3.6/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/home/doudz/MEGA/Dev/zigate/zigate/core.py", line 318, in decode_data
    response = RESPONSES.get(msg_type, Response)(value, rssi)
  File "/home/doudz/MEGA/Dev/zigate/zigate/responses.py", line 45, in __init__
    self.decode()
  File "/home/doudz/MEGA/Dev/zigate/zigate/responses.py", line 106, in decode
    sdata, msg_data = self.__decode(fmt, keys, msg_data)
  File "/home/doudz/MEGA/Dev/zigate/zigate/responses.py", line 117, in __decode
    sdata = OrderedDict(zip(keys, struct.unpack(fmt, data[:size])))
struct.error: unpack requires a buffer of 14 bytes

**Comment by doudz** [comment]
fix commited, to check
