### ISSUE TITLE
Zigate KeyError: 'ieee'

### ISSUE THREAD

**Issue by chpeps** [doudz/zigate#14]
j'ai un zigate-USB-TTL et un detecteur d'inondation aqara, quand le detecteur detecte une inondation j'ai ce message d'erreur dans la console python3.6.
Ce message apparait même avec le bouton de Xiaomi (rond) ainsi que le double switch.
j'ai utilisé pip3.6 install zigate==0.16.5 pour installer la lib zigate.

`Device not found, create it (this isn't normal)
Exception in thread Thread-31:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/thibaud/Documents/TMC/01_Powerail/01_Raspower/Docker/docker_raspower/venv/lib/python3.6/site-packages/zigate/transport.py", line 61, in packet_received
    dispatcher.send(ZIGATE_PACKET_RECEIVED, packet=raw_message)
  File "/Users/thibaud/Documents/TMC/01_Powerail/01_Raspower/Docker/docker_raspower/venv/lib/python3.6/site-packages/pydispatch/dispatcher.py", line 338, in send
    **named
  File "/Users/thibaud/Documents/TMC/01_Powerail/01_Raspower/Docker/docker_raspower/venv/lib/python3.6/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/Users/thibaud/Documents/TMC/01_Powerail/01_Raspower/Docker/docker_raspower/venv/lib/python3.6/site-packages/zigate/core.py", line 327, in decode_data
    dispatcher.send(ZIGATE_RESPONSE_RECEIVED, self, response=response)
  File "/Users/thibaud/Documents/TMC/01_Powerail/01_Raspower/Docker/docker_raspower/venv/lib/python3.6/site-packages/pydispatch/dispatcher.py", line 338, in send
    **named
  File "/Users/thibaud/Documents/TMC/01_Powerail/01_Raspower/Docker/docker_raspower/venv/lib/python3.6/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/Users/thibaud/Documents/TMC/01_Powerail/01_Raspower/Docker/docker_raspower/venv/lib/python3.6/site-packages/zigate/core.py", line 381, in interpret_response
    device = self._get_device(response['addr'])
  File "/Users/thibaud/Documents/TMC/01_Powerail/01_Raspower/Docker/docker_raspower/venv/lib/python3.6/site-packages/zigate/core.py", line 417, in _get_device
    self._set_device(d)
  File "/Users/thibaud/Documents/TMC/01_Powerail/01_Raspower/Docker/docker_raspower/venv/lib/python3.6/site-packages/zigate/core.py", line 442, in _set_device
    d = self.get_device_from_ieee(device.ieee)
  File "/Users/thibaud/Documents/TMC/01_Powerail/01_Raspower/Docker/docker_raspower/venv/lib/python3.6/site-packages/zigate/core.py", line 1351, in ieee
    return self.info['ieee']
KeyError: 'ieee'`

**Comment by doudz** [comment]
Je vois le problème.
Normalement au démarrage la lib récupère la liste des devices connus dans la zigate.
Dans ton cas il semble que le device n'était pas la liste d'où le message *Device not found, create it (this isn't normal)*
Mais l'adresse IEEE est manquante et comme c'est une information essentielle, ça plante rapidement.

Le fait qu'un équipement soit bien appairé mais absent de la liste interne de la Zigate est un bug du firmware qui a déjà été signalé.

Merci en tout cas d'avoir remonté le problème.
Je vais voir comment je peux contourner le souci

**Comment by doudz** [comment]
Je viens de faire une correction pour contourner le problème, je dois encore faire quelques tests

**Comment by doudz** [comment]
Corrigé dans la version 0.17.1

**Comment by doudz** [comment]
Nouvelle correction dans la version 0.17.2
Je vais faire encore quelques tests avant de clôturer
