### ISSUE TITLE
Failed to load persistent if it contains lumi wleak sensor

### ISSUE THREAD

**Issue by doudz** [doudz/zigate#65]
```
2019-01-04 18:32:57 ERROR (Thread-21) [zigate] Traceback (most recent call last):
  File "/home/pi/.homeassistant/deps/lib/python3.5/site-packages/zigate/core.py", line 238, in load_state
    device = Device.from_json(data, self)
  File "/home/pi/.homeassistant/deps/lib/python3.5/site-packages/zigate/core.py", line 1945, in from_json
    cluster = Cluster.from_json(cl, endpoint)
  File "/home/pi/.homeassistant/deps/lib/python3.5/site-packages/zigate/clusters.py", line 138, in from_json
    cluster.update(attribute)
  File "/home/pi/.homeassistant/deps/lib/python3.5/site-packages/zigate/clusters.py", line 418, in update
    zone_id = data['zone_id']
KeyError: 'zone_id'

```

**Comment by doudz** [comment]
Fix https://github.com/doudz/zigate/commit/af801d1f762790f650b6626aa71908d5cba418de
