### ISSUE TITLE
'NoneType' object is not iterable

### ISSUE THREAD

**Issue by doudz** [doudz/zigate#8]
```
Exception in thread Thread-1506:
Traceback (most recent call last):
File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
self.run()
File "/usr/lib/python3.5/threading.py", line 862, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.5/dist-packages/zigate/transport.py", line 36, in packet_received
dispatcher.send(ZIGATE_PACKET_RECEIVED, packet=raw_message)
File "/usr/lib/python3/dist-packages/pydispatch/dispatcher.py", line 338, in send
**named
File "/usr/lib/python3/dist-packages/pydispatch/robustapply.py", line 55, in robustApply
return receiver(*arguments, **named)
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 294, in decode_data
dispatcher.send(ZIGATE_RESPONSE_RECEIVED, self, response=response)
File "/usr/lib/python3/dist-packages/pydispatch/dispatcher.py", line 338, in send
**named
File "/usr/lib/python3/dist-packages/pydispatch/robustapply.py", line 55, in robustApply
return receiver(*arguments, **named)
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 357, in interpret_response
response['attribute'], True)
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 1343, in get_attribute
attr.update(attribute)
TypeError: 'NoneType' object is not iterable
```

**Comment by doudz** [comment]
Fix https://github.com/doudz/zigate/commit/0d20590fde8b25462f1fa61debe2be115b70d6a9
